openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: Checks server status
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
        description: ''
components:
  schemas: {}
