openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: blablahome API
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Server Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                required:
                  - status
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        description: ''
  /users:
    post:
      summary: Users
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - status
              examples:
                valid user:
                  value:
                    status: ok
                    user:
                      id: '82317456129'
                      name: Ivan
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: string
                required:
                  - status
                  - error
              examples:
                error:
                  value:
                    status: error
                    error: Some error reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      description: User registration
  /activities:
    post:
      summary: Ideas
      operationId: post-activities
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    status: error
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
              examples:
                without a name and description:
                  value:
                    errors:
                      description:
                        - "can't be blank"
                      name:
                        - "can't be blank"
      security:
        - Bearer authorization: []
      description: Creates new activity
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                cover:
                  type: string
              required:
                - name
                - description
        description: Use http uploaded file for cover attribute.
    get:
      summary: ''
      operationId: get-activities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
      description: List activities
    parameters: []
  '/activities/{activity_id}/participations':
    post:
      summary: Participations
      operationId: 'post-activities-:id-participations'
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    id: c59c229e-3a53-462c-b4e2-2d41c07f59b3
                    progress: 0
                    completed_at: null
                    user:
                      id: 0ac2009f-584b-4462-906a-4d1028d32e5f
                      name: Pavel Lazureykis
                    activity:
                      cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
                      days: 7
                      description: Testing
                      id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
                      name: Test
      description: Create participation. User joins the activity.
      security:
        - Bearer authorization: []
    parameters:
      - schema:
          type: string
        name: activity_id
        in: path
        required: true
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Activity:
      title: Activity
      type: object
      x-examples:
        example:
          id: '12357'
          name: Do something
          description: Multiline description
          cover: 'https://cover.image/url.jpg'
          days: 7
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        cover:
          type: string
      description: ''
    Participation:
      title: Participation
      type: object
      description: "User's participation in Activity"
      properties:
        id:
          type: string
        progress:
          type: integer
          example: '2'
          minimum: 0
          maximum: 7
        completed_at:
          type:
            - string
            - 'null'
          format: date-time
          example: '2020-04-03T11:23:15'
        user:
          $ref: '#/components/schemas/User'
        activity:
          $ref: '#/components/schemas/Activity'
      required:
        - id
        - progress
        - completed_at
        - user
        - activity
      x-examples:
        example-1:
          id: d77f0583-82f0-4565-9e99-70864d3cb9ab
          progress: 0
          completed_at: '2020-04-03T11:23:15'
          user:
            id: 0ac2009f-584b-4462-906a-4d1028d32e5f
            name: Pavel Lazureykis
          activity:
            cover: 'https://storage.googleapis.com/blablahome/uploads/activities/covers/62bed2d2-1ce4-49c0-a068-031d69aa1117/0.jpeg?v=63753130513'
            days: 7
            description: Testing
            id: 62bed2d2-1ce4-49c0-a068-031d69aa1117
            name: Test
  securitySchemes:
    Bearer authorization:
      name: Authorization
      type: apiKey
      in: header
      description: Used for protected endpoints
