openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths: {}
components:
  schemas: {}
