openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: blablahome API
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Server Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                required:
                  - status
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        description: ''
  /users:
    post:
      summary: Users
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - status
              examples:
                valid user:
                  value:
                    status: ok
                    user:
                      id: '82317456129'
                      name: Ivan
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: string
                required:
                  - status
                  - error
              examples:
                error:
                  value:
                    status: error
                    error: Some error reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      description: User registration
  /ideas:
    post:
      summary: Ideas
      operationId: post-ideas
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Idea'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    status: error
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
              examples:
                without a name and description:
                  value:
                    errors:
                      description:
                        - "can't be blank"
                      name:
                        - "can't be blank"
      security:
        - Bearer authorization: []
      description: Creates new idea
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                cover:
                  type: string
              required:
                - name
                - description
        description: Use http uploaded file for cover attribute.
    get:
      summary: ''
      operationId: get-ideas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Idea'
      description: List ideas
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Idea:
      title: Idea
      type: object
      x-examples:
        example:
          id: '12357'
          name: Do something
          description: Multiline description
          cover: 'https://cover.image/url.jpg'
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        cover:
          type: string
      description: ''
  securitySchemes:
    Bearer authorization:
      name: Authorization
      type: apiKey
      in: header
      description: Used for protected endpoints
