openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: blablahome API
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Server Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                required:
                  - status
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        description: ''
  /users:
    post:
      summary: Users
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                  user:
                    $ref: '#/components/schemas/User'
                  error:
                    type: string
                required:
                  - status
              examples:
                valid user:
                  value:
                    status: ok
                    user:
                      name: Ivan
                    auth_token: '123456'
                error:
                  value:
                    status: error
                    error: Some error reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      description: User registration
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        name:
          type: string
