openapi: 3.0.0
info:
  title: API v1
  version: '1.0'
  description: blablahome API
servers:
  - url: 'https://blablahome.lazureykis.dev/api'
    description: prod
  - url: 'http://localhost:4000/api'
    description: dev
paths:
  /status:
    get:
      summary: Server Status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                      - error
                required:
                  - status
      operationId: get-status
      description: Healthcheck endpoint
      requestBody:
        description: ''
components:
  schemas: {}
